"""Bake `recon/*.py` into the Colab notebook so it can never be stale.

The notebook used to pull `recon/` from Drive, a `GD_TOKEN` clone, or a hand-made
`recon.zip` upload. All three drift: the repo is private, so the common path was uploading a
zip from Downloads, and an old zip fails as `python3 <missing>.py` -> exit 2, which looks
exactly like an argparse error and reaches the cell with its stderr thrown away.

Embedding removes the moving part. The scripts travel *inside* the notebook, so pulling the
notebook is the only step, and the version that runs is by construction the version that was
committed with it.

    python colab/embed_recon.py            # re-bake after changing anything in recon/
    python colab/embed_recon.py --check    # exit 1 if the notebook is out of date

Run `--check` before committing a recon/ change; that is the whole anti-drift mechanism.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
NB = REPO / "colab" / "lingbot_map_colab.ipynb"
RECON = REPO / "recon"
MARKER = "RECON_BLOB"          # identifies the generated cell


def build_blob() -> tuple[str, str, list[str]]:
    """Deterministic zip of recon/*.py -> (base64, sha256, filenames)."""
    names = sorted(p.name for p in RECON.glob("*.py"))
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for n in names:
            # Fixed timestamp: otherwise the blob churns on every mtime change and every
            # commit shows a 64 KB diff for nothing.
            info = zipfile.ZipInfo(n, date_time=(1980, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, (RECON / n).read_bytes())
    raw = buf.getvalue()
    return base64.b64encode(raw).decode(), hashlib.sha256(raw).hexdigest(), names


def render_cell(blob: str, sha: str, names: list[str]) -> str:
    wrapped = "\n".join(blob[i:i + 100] for i in range(0, len(blob), 100))
    return f'''# {MARKER} -- generated by colab/embed_recon.py, do not edit by hand.
# recon/*.py travels inside this notebook: {len(names)} files, sha256 {sha[:16]}
# Re-bake with `python colab/embed_recon.py` after changing anything in recon/.
import base64, hashlib, io, os, pathlib, zipfile

RECON_SHA = "{sha}"
RECON_B64 = """\\
{wrapped}"""

RECON = pathlib.Path(os.environ.get("RECON_SRC", "/content/recon"))
if "RECON_SRC" in os.environ:
    # Escape hatch: point at a live clone or a Drive copy to override the baked-in copy.
    print(f"RECON_SRC set -- using {{RECON}} instead of the embedded scripts")
else:
    raw = base64.b64decode(RECON_B64)
    got = hashlib.sha256(raw).hexdigest()
    assert got == RECON_SHA, f"embedded blob corrupted: {{got}} != {{RECON_SHA}}"
    RECON.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(raw)) as z:
        z.extractall(RECON)
    print(f"unpacked {{len(list(RECON.glob('*.py')))}} scripts -> {{RECON}}  "
          f"(sha {{RECON_SHA[:16]}})")

missing = [n for n in {names!r} if not (RECON / n).exists()]
assert not missing, f"missing from RECON: {{missing}}"
print("  " + ", ".join(sorted(p.name for p in RECON.glob("*.py"))))
'''


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the notebook's embedded copy is stale")
    a = ap.parse_args()

    blob, sha, names = build_blob()
    nb = json.loads(NB.read_text(encoding="utf-8"))

    target = None
    for c in nb["cells"]:
        if c["cell_type"] == "code" and MARKER in "".join(c["source"]):
            target = c
            break
    if target is None:
        # First run: replace the old upload cell (the one that made recon.zip).
        for c in nb["cells"]:
            if c["cell_type"] == "code" and "recon.zip" in "".join(c["source"]):
                target = c
                break
    if target is None:
        raise SystemExit("could not find the recon cell to replace")

    new = render_cell(blob, sha, names)
    old = "".join(target["source"])

    if a.check:
        if old.strip() == new.strip():
            print(f"notebook is current ({len(names)} scripts, sha {sha[:16]})")
            return
        cur = "unknown"
        for line in old.splitlines():
            if line.startswith("RECON_SHA"):
                cur = line.split('"')[1][:16]
        print(f"STALE: notebook embeds {cur}, recon/ is {sha[:16]}\n"
              f"  fix: python colab/embed_recon.py", file=sys.stderr)
        raise SystemExit(1)

    target["source"] = new.splitlines(keepends=True)
    NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"baked {len(names)} scripts into {NB.name}  sha {sha[:16]}")
    for n in names:
        print(f"  {n}")


if __name__ == "__main__":
    main()
